# Quickstart tutorial
Source: https://numpy.org/doc/stable/user/quickstart.html

Learning Objectives

After reading, you should be able to:

- Understand the difference between one-, two- and n-dimensional arrays in NumPy;

- Understand how to apply some linear algebra operations to n-dimensional arrays without using for-loops;

- Understand axis and shape properties for n-dimensional arrays.


## The basics
- Main numpy object: `ndarray` - homogeneous (same data type) multidimensional array
- Indexed by non-negative integers
- Dimensions of a multidimensional array are called _axes_

## `ndarray`

- Numpy's array _class_ is called `ndarray`
- It is also known by its alias `array` 
- `numpy.array` != Python library class `array.array` which only handles 1D arrays 


In [2]:
import numpy as np
from numpy import pi

In [3]:
# returns values between [0,15) (step=1) shaped as a 3 x 5 matrix
a = np.arange(15).reshape(3, 5) # arange is similar to range but returns a numpy array.
b = np.array([6,7,8])
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


- Most important attributes of `ndarray` object are:
    - `ndarray.ndim` : Number of axes of the array
    - `ndarray.shape`: Dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.
    - `ndarray.size` : the total number of elements of the array. Equal to the product of #rows * #cols aka elements of `shape`
    - `ndarray.dtype` : an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.
    - `ndarray.itemsize` : the size in bytes of each element of the array. E.g., an array of elements of type `float64` has `itemsize` 8 (=64/8), while one of type `complex32` has `itemsize` 4 (=32/8). It is equivalent to `ndarray.dtype.itemsize`
    - `ndarray.data` : the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

In [4]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [6]:
a.dtype.name

'int64'

In [7]:
a.itemsize

8

In [8]:
type(a)

numpy.ndarray

## Array creation
- Multiple ways to create an array
    1. Using the `np.array` like `a = np.array([2,3,4])`
    2. Using `np.arange` like `a=np.arange(2,5)`
- A note about `arange`: 
> When arange is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function linspace that receives as an argument the number of elements that we want, instead of the step:



In [9]:
np.linspace(0, 2, 9)                   # 9 numbers from 0 to 2
x = np.linspace(0, 2 * pi, 100)        # useful to evaluate function at lots of points
f = np.sin(x)

## Printing Arrays
NumPy displays arrays similar to nested python lists, but with the following layout:
- the last axis is printed from left to right,
- the second-to-last is printed from top to bottom,
- the rest are also printed from top to bottom, with each slice separated from the next by an empty line.


In [10]:
a = np.arange(6)                    # 1d array
print(f"a is:\n{a}\n")
b = np.arange(12).reshape(4, 3)     # 2d array
print(f"b is:\n{b}\n")
c = np.arange(24).reshape(2, 3, 4)  # 3d array
print(f"c is:\n{c}\n")


a is:
[0 1 2 3 4 5]

b is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

c is:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]



If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners:

In [11]:
print(np.arange(10000))
print()
print(np.arange(10000).reshape(100, 100))

[   0    1    2 ... 9997 9998 9999]

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


To disable this behaviour and force NumPy to print the entire array, you can change the printing options using `set_printoptions`

`np.set_printoptions(threshold=sys.maxsize)  # sys module should be imported`

## Basic operations
- Arithmetic operators on arrays apply elementwise.

In [19]:
a = np.array([25, 13, 78, 99])
b = np.linspace(7, 9, 4)
print(f"a is:\n{a}\n")
print(f"b is:\n{b}\n")

c = a + b
d = 2*b

print(f"a + b is:\n{c}\n")  # elementwise addition
print(f"2*b is:\n{d}\n") # scalar multiplication
print(f"a*b is:\n{a*b}\n") # elementwise multiplication


a is:
[25 13 78 99]

b is:
[7.         7.66666667 8.33333333 9.        ]

a + b is:
[ 32.          20.66666667  86.33333333 108.        ]

2*b is:
[14.         15.33333333 16.66666667 18.        ]

a*b is:
[175.          99.66666667 650.         891.        ]



Unlike in many matrix languages, the product operator `*` operates elementwise in NumPy arrays. The matrix product can be performed using the `@` operator (in python >=3.5) or the `dot` function or method:

In [ ]:
A = np.random.randint(4,size=(2,2))
B = np.random.randint(4,size=(2,2))
print(f"A is:\n{A}\n")
print(f"B is:\n{B}\n")

print(f"A * B is \n{A * B}\n") # elementwise product
print(f"A @ B is \n{A @ B}\n") # 1st method to compute matrix product
print(f"A.dot(B) is \n{A.dot(B)}\n") # 2nd method to compute matrix product

A is:
[[0 3]
 [2 1]]

B is:
[[3 2]
 [3 2]]

A * B is 
[[0 6]
 [6 2]]

A @ B is 
[[9 6]
 [9 6]]

A.dot(B) is 
[[9 6]
 [9 6]]

