# Quickstart tutorial
Source: https://numpy.org/doc/stable/user/quickstart.html

Learning Objectives

After reading, you should be able to:

- Understand the difference between one-, two- and n-dimensional arrays in NumPy;

- Understand how to apply some linear algebra operations to n-dimensional arrays without using for-loops;

- Understand axis and shape properties for n-dimensional arrays.


## The basics
- Main numpy object: `ndarray` - homogeneous (same data type) multidimensional array
- Indexed by non-negative integers
- Dimensions of a multidimensional array are called _axes_

## `ndarray`

- Numpy's array _class_ is called `ndarray`
- It is also known by its alias `array` 
- `numpy.array` != Python library class `array.array` which only handles 1D arrays 
- Most important attributes of `ndarray` object are:
    - `ndarray.ndim` : Number of axes of the array
    - `ndarray.shape`: Dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.
    - `ndarray.size` : the total number of elements of the array. Equal to the product of #rows * #cols aka elements of `shape`
    - `ndarray.dtype` : an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.
    - `ndarray.itemsize` : the size in bytes of each element of the array. E.g., an array of elements of type `float64` has `itemsize` 8 (=64/8), while one of type `complex32` has `itemsize` 4 (=32/8). It is equivalent to `ndarray.dtype.itemsize`
    - `ndarray.data` : the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

In [3]:
import numpy as np

In [ ]:
# returns values between [0,15) (step=1) shaped as a 3 x 5 matrix
a = np.arange(15).reshape(3, 5)
b = np.array([6,7,8])
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [5]:
a.shape

(3, 5)

In [6]:
a.ndim

2

In [8]:
a.dtype.name

'int64'

In [9]:
a.itemsize

8

In [10]:
type(a)

numpy.ndarray